<a href="https://colab.research.google.com/github/SwethaS-07/ai-ml-journey/blob/main/day%205.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

In [2]:
arr = np.zeros(10)

In [3]:
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [4]:
mat = np.zeros((10,2))
print(mat)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [6]:
tri = np.zeros((2,10,2))
print(tri)

[[[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]]


In [5]:
 arr1 = np.ones((2,3))
 print(arr1)


[[1. 1. 1.]
 [1. 1. 1.]]


In [6]:
arr2 = np.full(2,3)

In [7]:
print(arr2)


[3 3]


In [14]:
arr = np.eye(3)
print(arr)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [9]:
print(np.empty(3))

[1. 1. 1.]


In [10]:
print(np.arange(0,100,2))

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98]


In [11]:
print(np.linspace(0,100,6))

[  0.  20.  40.  60.  80. 100.]


In [13]:
print(np.sum(arr))

3.0
3.0


In [15]:
print(np.mean(arr))

0.3333333333333333


In [16]:
print(np.median(arr))

0.0


In [18]:
print(np.min(arr))

0.0


In [19]:
print(np.max(arr))

1.0


In [20]:
print(np.std(arr))

0.4714045207910317


In [21]:
print(np.var(arr))

0.2222222222222222


In [22]:
print(np.argmin(arr))

1


In [23]:
print(np.argmax(arr))

0


In [24]:
print(np.sum(arr,axis=0))

[1. 1. 1.]


In [25]:
print(np.sum(arr,axis=1))

[1. 1. 1.]
