<a href="https://colab.research.google.com/github/SwethaS-07/ai-ml-journey/blob/main/day02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [3]:
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
print(arr[0]) #zero based indexing

[1 2 3]


In [5]:
print(arr[-1])

[7 8 9]


In [6]:
print(arr[0][2])

3


In [7]:
print(arr[0,2])

3


In [8]:
print(arr[0:3:2])

[[1 2 3]
 [7 8 9]]


In [9]:
print(arr[::-1])

[[7 8 9]
 [4 5 6]
 [1 2 3]]


In [10]:
print(arr)
print(arr[:,0:1]) #row , column

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1]
 [4]
 [7]]
