<a href="https://colab.research.google.com/github/SwethaS-07/ai-ml-journey/blob/main/day01_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
array = [1,2,3,4,5]

In [ ]:
print(type(array))

<class 'list'>


In [ ]:
array = np.array(array)

In [ ]:
print(type(array))

<class 'numpy.ndarray'>


In [ ]:
array = array*2

In [ ]:
print(array)

[ 2  4  6  8 10]


In [ ]:
brr = np.array([1,2,3,4,5])

In [ ]:
print(array+brr)

[ 3  6  9 12 15]


In [ ]:
#DataTypes : int,floor,string,boolean,object and convert the datatype

in int there are 4 types:
int8 (1 bits = 1 bytes) -128 t0 127,
int16(1 bits = 2 bytes) -32768 to 32767,
int32 (1 bits = 4 bytes) -2147483648 to 2147483647,
int64(1 bits = 8 bytes)
float same as int but in float starts with float16


In [ ]:
print(array.dtype)

int64


In [ ]:
array = np.array([1,2,3,4,5],dtype = np.int8)

In [ ]:
print(array.dtype)
print(f"array.nbytes {array.nbytes} bytes")

int8
array.nbytes 5 bytes


String,bool,object


In [ ]:
array = np.array([1,2,3,4,5],dtype  = np.str_)
print(array.dtype)
array = np.array([True,False],dtype=np.bool_)
print(array.dtype)
array = np.array([True,False,1,"Swetha"],dtype=np.object_)

<U1
bool


In [ ]:
print(array.dtype)

object


converting


In [ ]:
print(array.astype(np.str_))

['True' 'False' '1' 'Swetha']


Arrays - 1D,2D,MD arrays
Shapes and reshape

In [ ]:
a = np.array(1) #0 dimension
print(a.ndim)
print(a)

0
1


In [ ]:
arr = np.array([1,2,3,4,5]) #1D

In [ ]:
mat = np.array([[1,2,3],[4,5,6]]) #2D
mat1 = np.array([[[1,2,3],
                  [4,5,6]],
                [[7,8,9],
                 [10,11,12]]]) #3D

In [ ]:
print(arr.ndim)
print(mat.ndim)
print(mat1.ndim)
print(arr)
print(mat)
print(mat1)

1
2
3
[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
#accessing
print(arr[0])
print(mat[0][0])
print(mat1[0][0][0])
#or
print(mat1[0,0,0])

1
1
1
1


In [ ]:
#shape
print(mat1.shape)

(2, 2, 3)


In [ ]:
#Reshape
array = arr.reshape(5,1)
print(array)

[[1]
 [2]
 [3]
 [4]
 [5]]


In [ ]:
array = array.reshape(1,-1)

In [ ]:
print(array)

[[1 2 3 4 5]]
