<a href="https://colab.research.google.com/github/SwethaS-07/ai-ml-journey/blob/main/day03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
arr = np.array([25,24,5,2])

In [3]:
print(arr+1)

[26 25  6  3]


In [4]:
print(arr-5)

[20 19  0 -3]


In [5]:
print(arr*5)

[125 120  25  10]


In [6]:
print(arr/5)

[5.  4.8 1.  0.4]


In [7]:
print(arr**5)

[9765625 7962624    3125      32]


In [8]:
#functions

In [11]:
brr = np.sqrt(arr)
print(brr)

[5.         4.89897949 2.23606798 1.41421356]


In [13]:
print(np.round(brr))

[5. 5. 2. 1.]


In [14]:
print(np.floor(brr))

[5. 4. 2. 1.]


In [15]:
print(np.ceil(brr))

[5. 5. 3. 2.]


In [16]:
# two arrays operations

In [17]:
arr = np.array([1,2,3,4])

In [18]:
brr = np.array([5,6,7,8])

In [19]:
print(arr+brr)

[ 6  8 10 12]


In [20]:
print(arr-brr)

[-4 -4 -4 -4]


In [21]:
print(arr*brr)

[ 5 12 21 32]


In [22]:
print(brr/arr)

[5.         3.         2.33333333 2.        ]


In [23]:
#constants

In [24]:
print(np.pi)

3.141592653589793


In [25]:
#comparison operator

In [26]:
age = np.array([25,26,78,90,40,35])

In [27]:
print(age<18)

[False False False False False False]


In [28]:
print(age>18)

[ True  True  True  True  True  True]
