<a href="https://colab.research.google.com/github/SwethaS-07/ai-ml-journey/blob/main/day_06.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
marks = np.array([50,60,65,100,76])
print(marks)

[ 50  60  65 100  76]


In [3]:
print(marks[marks>50])

[ 60  65 100  76]


In [4]:
print(marks>50)

[False  True  True  True  True]


In [5]:
passMark = marks[marks>50]
print(passMark)

[ 60  65 100  76]


In [6]:
even = marks[marks%2==0]
print(even)

[ 50  60 100  76]


In [7]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [8]:
even = np.where(arr%2==0,arr,0)
print(even)

[[0 2 0]
 [4 0 6]]
