<a href="https://colab.research.google.com/github/SwethaS-07/ai-ml-journey/blob/main/day_07.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import os
print(os.getcwd())

/content


In [2]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4,5])

In [4]:
np.save("data.npy",arr)

In [5]:
read = np.load("data.npy")
print(read)

[1 2 3 4 5]


In [6]:
brr = np.array([6,7,8,9,0])

In [7]:
np.savez("data.npz",arr,brr)

In [8]:
read = np.load("data.npz")

In [9]:
print(read)

NpzFile 'data.npz' with keys: arr_0, arr_1


In [10]:
print(read["arr_0"])

[1 2 3 4 5]


In [11]:
print(read["arr_1"])

[6 7 8 9 0]


In [12]:
a = np.array([
    [1,2],[3,4]
])
b = np.array([
    [4,2],[7,4]
])


In [13]:
print(np.matmul(a,b))

[[18 10]
 [40 22]]


In [15]:
a = np.array([1,2,3])
b= np.array([4,5,6])

print(np.dot(a,b))

32


In [16]:
b = np.array([
    [4,2],[7,4]
])
print(b.T)

[[4 7]
 [2 4]]


In [17]:
print(np.linalg.det(b))

1.999999999999999
